"""Command-line interface — one subcommand per phase.

Usage:

    # First-time setup
    sift init --root ./index
    sift seed --root ./index --from-json www.ato.gov.au_....json
    sift seed --root ./index --from-sitemap https://www.ato.gov.au/sitemap.xml

    # Each run is a sequence of resumable phases. New run-id is generated by
    # `plan` (or pass --run-id to resume an existing run).
    sift plan    --root ./index
    sift fetch   --root ./index --run-id <id> [--limit N] [--rate 2.0]
    sift extract --root ./index --run-id <id>
    sift commit  --root ./index --run-id <id>
    sift publish --root ./index --run-id <id>

    # One-shot convenience (still safe to interrupt at any phase)
    sift run --root ./index [--limit N]

    # Inspection
    sift status --root ./index
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import click

from . import CRAWLER_VERSION, paths
from . import classify as classify_mod
from . import decide as decide_mod
from . import integrity as integrity_mod
from . import publish as publish_mod
from . import sites as sites_mod
from .classify import (
    CLASSIFIER_VERSION,
    DEFAULT_EXCLUDE_PATTERNS,
    canonicalize_url,
    classify_tier,
    compile_excludes,
    is_excluded,
    is_malformed_url,
    parent_guide,
)
from .commit import commit as commit_phase
from .config import IndexConfig, load_config
from .extract import EXTRACTOR_VERSION, extract_all
from .fetch import FetchInput, fetch_all
from .manifest import (
    counts_by_state,
    init_schema,
    now_utc,
    open_db,
    record_run_end,
    record_run_phase,
    record_run_start,
    transaction,
    upsert_seed,
)
from .normalize import NORMALIZER_VERSION
from .plan import load_plan, plan as plan_phase
from .publish import build_artifacts, publish as publish_phase


def _root_opt(f):
    return click.option(
        "--root", required=True, type=click.Path(path_type=Path),
        help="Index root directory (manifest.db + runs/ live here)",
    )(f)


def _config_opt(f):
    """Shared --config flag. Defaults to sift.toml in cwd."""
    return click.option(
        "--config", "config_path", type=click.Path(exists=False, path_type=Path),
        default=None,
        help="Path to config TOML. Defaults to ./sift.toml or "
             "./sift.local.toml if present.",
    )(f)


def _load_cli_config(path: Optional[Path]) -> IndexConfig:
    """Load the config file, apply it to all modules with tunable knobs,
    and return the merged IndexConfig. Idempotent.

    Order matters: load + set the site profile FIRST, then the rest. Many
    modules read `current_profile()` at call-time; setting it after the
    config-tunables landed could leave a window where they disagree.
    """
    cfg = load_config(path)
    # 1. Site profile (must come first; classify/normalize/agent_surface/facts
    #    delegate to it for site-specific decisions)
    sites_mod.set_profile(sites_mod.load_profile(cfg.site.profile))
    # 2. Operational tunables
    classify_mod.set_current_fy_start_year(cfg.current_fy_start_year)
    decide_mod.apply_config(cfg)
    publish_mod.apply_config(cfg)
    # 3. Browser stack — the availability probe is DEFERRED to the fetch
    #    phase (see run/fetch), and fires only when a SPA URL is actually
    #    pending. Probing here would hard-fail every command (even `status`,
    #    `extract`, `publish`, or a fully-HTTP `run`) the moment config has
    #    [browser].enabled=true but the optional dep is missing — so a box
    #    that lost Playwright couldn't index its HTTP-only majority at all.
    return cfg


def _new_run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


@contextmanager
def _fail_run_on_crash(conn, run_id: str):
    """Record a terminal ``failed`` run status if the wrapped phase crashes.

    Every phase command writes a non-terminal phase marker
    (``record_run_phase``) on entry. Without this guard, an exception
    mid-phase leaves ``runs.status`` stuck at ``running`` forever, so
    ``index_status`` / ``status`` make an agent poll-loop indefinitely. We
    record a best-effort ``failed`` (the run row may not exist yet for a
    bare ``sift fetch`` — then the UPDATE matches nothing, which is fine),
    then re-raise so Click still surfaces the error and exit code 1.

    A *degraded* run exits via ``sys.exit(2)`` → ``SystemExit``, which is
    NOT an ``Exception`` subclass, so this guard does not catch it and the
    already-recorded ``degraded`` status stands. Applied uniformly to
    ``run`` and every standalone phase command so none of them can strand
    a run row — the generalization of the original ``run``-only fix.
    """
    try:
        yield
    except Exception as e:
        try:
            with transaction(conn):
                record_run_end(
                    conn, run_id, now_utc(), "failed", "{}",
                    error=f"{type(e).__name__}: {e}"[:1000],
                )
        except Exception:
            pass
        raise


def _build_firecrawl_pool(cfg: IndexConfig, flag_enable: bool):
    """Construct a FirecrawlScrapePool when the fallback is enabled (via flag
    or config) AND ``FIRECRAWL_API_KEY`` is set.

    Returns ``None`` when disabled. When enabled but the API key is missing,
    emits a warn line and returns ``None`` — the run continues with
    native-only fetching rather than crashing. This matches the discovery
    integration's ``FirecrawlError → warn`` pattern.
    """
    enabled = flag_enable or cfg.crawl.firecrawl.enabled
    if not enabled:
        return None
    if not os.environ.get("FIRECRAWL_API_KEY"):
        click.echo(
            "warn: --firecrawl-fallback enabled but FIRECRAWL_API_KEY is "
            "not set; falling back to native-only fetch.",
            err=True,
        )
        return None
    from .sources.firecrawl import FirecrawlScrapePool
    return FirecrawlScrapePool(cfg.crawl.firecrawl)


@click.group()
def main():
    """Deterministic website indexer (site-agnostic, profile-driven)."""


@main.command()
@_root_opt
def init(root: Path):
    """Initialize manifest.db schema. Idempotent — won't clobber existing state.

    Surfaces the changelog state so the operator knows whether they're
    extending a chain or starting fresh."""
    manifest_existed = paths.manifest_path(root).exists()
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)

    cl = paths.changelog_path(root)
    cl_entries = 0
    cl_genesis = None
    if cl.exists():
        with cl.open() as f:
            for line in f:
                if not line.strip():
                    continue
                cl_entries += 1
                if cl_genesis is None:
                    try:
                        cl_genesis = json.loads(line).get("run_id")
                    except json.JSONDecodeError:
                        continue

    out = {
        "manifest_path": str(paths.manifest_path(root)),
        "manifest_existed": manifest_existed,
        "changelog_path": str(cl),
        "changelog_entries": cl_entries,
        "changelog_genesis_run": cl_genesis,
    }
    click.echo(json.dumps(out, indent=2))
    if cl_entries > 0:
        click.echo(
            f"\nNote: preserving existing changelog ({cl_entries} entries, "
            f"chain from {cl_genesis}). Any future commits will extend the chain.",
            err=True,
        )


@main.command()
@_root_opt
@_config_opt
@click.option("--from-json", "json_path", type=click.Path(exists=True, path_type=Path),
              help="Seed from a {links:[{url,...}, ...]} discovery dump")
@click.option("--from-sitemap", "sitemap_url", type=str,
              help="Seed by fetching one sitemap.xml URL (recursive on sitemap-index)")
@click.option("--from-domain", "domain_url", type=str, default=None,
              help="Seed by auto-discovering every sitemap for a domain. "
                   "Parses robots.txt's Sitemap: directives + probes "
                   "well-known paths (/sitemap.xml, /sitemap_index.xml, "
                   "/wp-sitemap.xml, ...) + handles gzipped + plain-text "
                   "fallback. Use this when you only know the domain.")
@click.option("--from-firecrawl-map", "firecrawl_map_url", type=str, default=None,
              help="Seed by Firecrawl /v2/map (blended sitemap + cached crawl + SERP). "
                   "Closes the discovery gap for sites with no sitemap, sparse sitemaps, "
                   "or bot-blocked sitemap fetches. Requires FIRECRAWL_API_KEY env.")
@click.option("--firecrawl-limit", type=int, default=500, show_default=True,
              help="Max URLs to request from --from-firecrawl-map.")
@click.option("--firecrawl-search", type=str, default=None,
              help='Server-side keyword filter for --from-firecrawl-map results '
                   '(e.g. "authentication" to scope discovery within a large site).')
@click.option("--firecrawl-include-subdomains", is_flag=True, default=False,
              help="Include subdomain URLs in --from-firecrawl-map results.")
@click.option("--host-allow", multiple=True, default=(),
              help="Only seed URLs on these hosts (default: config seed.host_allow)")
@click.option("--exclude", "extra_excludes", multiple=True, default=(),
              help="Additional regex patterns; URLs matching any are skipped.")
@click.option("--no-default-excludes", is_flag=True,
              help="Disable built-in excludes (/sitemap*, /api/*, /print/*, etc.).")
def seed(root: Path, config_path: Optional[Path],
         json_path: Optional[Path], sitemap_url: Optional[str],
         domain_url: Optional[str],
         firecrawl_map_url: Optional[str],
         firecrawl_limit: int, firecrawl_search: Optional[str],
         firecrawl_include_subdomains: bool,
         host_allow: tuple[str, ...],
         extra_excludes: tuple[str, ...], no_default_excludes: bool):
    """Add URLs to the manifest from a discovery dump, a sitemap, or Firecrawl.

    Each URL is canonicalized, classified, and upserted unless it matches an
    exclude pattern. CLI flags override config; if both are absent, defaults apply.

    Multiple sources can be combined in one invocation — every source's URLs
    flow through the same filter + upsert pipeline, so a mixed
    sitemap+Firecrawl seed is the same as two back-to-back runs.
    """
    from .sources import JsonFileSource, SeedSource
    from .sources.firecrawl import FirecrawlError, FirecrawlMapSource
    from .sources.sitemap import AutoSitemapSource, SitemapSource

    cfg = _load_cli_config(config_path)
    sources: list[SeedSource] = []
    if json_path:
        sources.append(JsonFileSource(json_path))
    if sitemap_url:
        sources.append(SitemapSource(sitemap_url, user_agent=cfg.crawl.user_agent))
    if domain_url:
        sources.append(AutoSitemapSource(domain_url, user_agent=cfg.crawl.user_agent))
    if firecrawl_map_url:
        sources.append(FirecrawlMapSource(
            firecrawl_map_url,
            limit=firecrawl_limit,
            search=firecrawl_search,
            include_subdomains=firecrawl_include_subdomains,
        ))
    if not sources:
        raise click.UsageError(
            "provide --from-json, --from-sitemap, --from-domain, or --from-firecrawl-map"
        )
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)

    # Excludes: CLI extras + (defaults OR none, per flag and config)
    use_defaults = not no_default_excludes and cfg.seed.use_default_excludes
    patterns = list(cfg.seed.extra_exclude_patterns) + list(extra_excludes)
    if use_defaults:
        patterns = list(DEFAULT_EXCLUDE_PATTERNS) + patterns
    excludes = compile_excludes(tuple(patterns))
    # Host allow: CLI wins; else config; else built-in default
    allowed_hosts = host_allow or cfg.seed.host_allow

    seeds: list[tuple[str, Optional[str]]] = []  # (url, lastmod_iso_or_None)
    for src in sources:
        try:
            for url, lm in src.discover():
                if url:
                    seeds.append((url, lm))
        except FirecrawlError as e:
            click.echo(f"warn: {src.name} discovery failed: {e}", err=True)

    allowed = {h.lower() for h in allowed_hosts}
    now = now_utc()
    inserted = reclassified = skipped_host = skipped_excluded = 0
    skipped_malformed = 0
    with transaction(conn):
        for raw_url, lm in seeds:
            url = canonicalize_url(raw_url)
            # Malformed-URL guard — catches the "Firecrawl /map returns
            # multi-URL concatenations" class that blew up Cornell LII in
            # the bench. See classify.is_malformed_url for the heuristics.
            if is_malformed_url(url):
                skipped_malformed += 1
                continue
            host = url.split("//", 1)[-1].split("/", 1)[0].lower()
            if host not in allowed:
                skipped_host += 1
                continue
            if is_excluded(url, excludes):
                skipped_excluded += 1
                continue
            tier = classify_tier(url).value
            pg = parent_guide(url)
            outcome = upsert_seed(
                conn, url, tier, pg, CLASSIFIER_VERSION, lm, now
            )
            if outcome == "inserted":
                inserted += 1
            elif outcome == "reclassified":
                reclassified += 1
    # Surface zero-result outcomes that previously left the operator with a
    # green-looking JSON summary and no signal that nothing was actually added.
    new_count = inserted + reclassified
    if not seeds:
        names = ", ".join(s.name for s in sources)
        click.echo(
            f"warn: discovery source(s) [{names}] yielded zero URLs. Common causes:\n"
            "  - source fetch failed (see warnings above)\n"
            "  - UA rejected by the server (try [crawl] user_agent = \"...\" in your config)\n"
            "  - sitemap-index referenced sub-sitemaps that all failed\n"
            "  - the source returned URLs in an unexpected shape",
            err=True,
        )
    elif seeds and new_count == 0:
        click.echo(
            f"warn: all {len(seeds)} discovered URL(s) were filtered out "
            f"(host_filter={skipped_host}, exclude_filter={skipped_excluded}). "
            f"Check [seed] host_allow ({list(allowed_hosts)}) and exclude patterns.",
            err=True,
        )
    if skipped_malformed:
        click.echo(
            f"warn: {skipped_malformed} discovered URL(s) were malformed "
            "(over-length or contained concatenation artifacts like '%20https:'). "
            "These almost always come from a discovery source that joined multiple "
            "links into one — check the upstream sitemap or /map source.",
            err=True,
        )
    click.echo(json.dumps({
        "seeded": len(seeds), "inserted": inserted, "reclassified": reclassified,
        "skipped_host": skipped_host, "skipped_excluded": skipped_excluded,
        "skipped_malformed": skipped_malformed,
        "exclude_patterns": patterns,
        "total_in_manifest": _total_rows(conn),
    }, indent=2))


def _total_rows(conn) -> int:
    return conn.execute("SELECT COUNT(*) FROM manifest").fetchone()[0]


def _read_only_urls(path: Path) -> set[str]:
    """Parse a one-URL-per-line file for ``sift run --only-urls``.

    Blank lines and lines starting with ``#`` are ignored. URLs are
    canonicalized with the same rules as ``sift seed`` so the plan-side
    set-membership check matches manifest rows regardless of how the
    caller wrote them (trailing slash, case, etc.)."""
    out: set[str] = set()
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        out.add(canonicalize_url(line))
    return out


@main.command()
@_root_opt
@_config_opt
@click.option("--run-id", default=None, help="Reuse an existing run-id (else generate)")
@click.option("--only-urls", "only_urls_path",
              type=click.Path(exists=True, path_type=Path), default=None,
              help="Scope the plan to URLs in this file (one per line; "
                   "blanks + # comments skipped). Same semantics as "
                   "`sift run --only-urls`.")
def plan(root: Path, config_path: Optional[Path], run_id: Optional[str],
         only_urls_path: Optional[Path]):
    """Phase 1: emit plan.jsonl with per-URL decisions."""
    cfg = _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)
    run_id = run_id or _new_run_id()
    pp = paths.plan_path(root, run_id)
    now = datetime.now(timezone.utc)
    with transaction(conn):
        record_run_start(conn, run_id, now_utc())
        record_run_phase(conn, run_id, "plan")
    only_urls = _read_only_urls(only_urls_path) if only_urls_path else None
    counts = plan_phase(
        conn, pp, now=now,
        extractor_version=EXTRACTOR_VERSION,
        normalizer_version=NORMALIZER_VERSION,
        profile=sites_mod.current_profile(),
        cfg=cfg,
        only_urls=only_urls,
    )
    click.echo(json.dumps({"run_id": run_id, "plan": str(pp), "counts": counts}, indent=2))


@main.command()
@_root_opt
@_config_opt
@click.option("--run-id", required=True)
@click.option("--limit", type=int, default=None,
              help="Stop after this many fetches (handy for smoke tests)")
@click.option("--rate", type=float, default=None,
              help="Requests per second per host (default: config crawl.rate_per_sec)")
@click.option("--concurrency", type=int, default=None,
              help="Concurrent in-flight requests (default: config crawl.concurrency)")
@click.option("--decisions", multiple=True, default=("FETCH", "FETCH_CONDITIONAL"),
              help="Only fetch URLs with these decisions")
@click.option("--tier", "tiers", multiple=True, default=(),
              help="Only fetch URLs in these tiers (repeat: --tier LIVING --tier NEWS). "
                   "Default = no tier filter.")
@click.option("--firecrawl-fallback", is_flag=True, default=False,
              help="On 401/403 from the native fetcher, escalate that URL via "
                   "Firecrawl /v2/scrape. Costs Firecrawl credits; capped per "
                   "[crawl.firecrawl] max_credits_per_run. Requires "
                   "FIRECRAWL_API_KEY env. Overrides config.")
def fetch(root: Path, config_path: Optional[Path], run_id: str,
          limit: Optional[int], rate: Optional[float],
          concurrency: Optional[int], decisions: tuple[str, ...],
          tiers: tuple[str, ...], firecrawl_fallback: bool):
    """Phase 2: fetch URLs per plan.jsonl. Idempotent; resumes via fetch.log."""
    cfg = _load_cli_config(config_path)
    rate = rate if rate is not None else cfg.crawl.rate_per_sec
    concurrency = concurrency if concurrency is not None else cfg.crawl.concurrency
    conn = open_db(paths.manifest_path(root))
    with _fail_run_on_crash(conn, run_id):
        record_run_phase(conn, run_id, "fetch")
        plan = load_plan(paths.plan_path(root, run_id))
        fetchable = [p for p in plan if p.decision in decisions]
        if tiers:
            tier_set = set(tiers)
            fetchable = [p for p in fetchable if p.tier in tier_set]
        if limit is not None:
            fetchable = fetchable[:limit]
        inputs = [
            FetchInput(url=p.url, decision=p.decision, etag=p.etag, last_modified=p.last_modified)
            for p in fetchable
        ]
        profile = sites_mod.current_profile()
        needs_browser = cfg.browser.enabled and any(
            profile.requires_browser(p.url) for p in fetchable
        )
        if needs_browser:
            # Deferred browser probe (see run): only hard-fail when a SPA URL
            # is actually pending, so a fully-HTTP fetch isn't blocked by a
            # missing optional dep.
            from .browser import check_browser_available
            check_browser_available()
        n_browser = sum(1 for p in fetchable if profile.requires_browser(p.url))
        click.echo(
            f"fetching {len(inputs)} URLs (rate={rate}/s, concurrency={concurrency}"
            + (f", browser={n_browser}" if needs_browser else "")
            + ")"
        )
        fetch_log = paths.fetch_log_path(root, run_id)

        statuses: dict[int, int] = {}
        def on_result(r):
            statuses[r.status] = statuses.get(r.status, 0) + 1

        fc_pool = _build_firecrawl_pool(cfg, firecrawl_fallback)

        async def _run() -> int:
            # BrowserPool is constructed only if a SPA URL is actually pending —
            # avoids the ~5-10s crawler startup for http-only runs that happen to
            # have [browser].enabled=true in config.
            pool = None
            if needs_browser:
                from .browser import BrowserPool
                pool = BrowserPool(cfg.browser.concurrency, cfg.browser)
            try:
                return await fetch_all(
                    inputs, root, fetch_log,
                    rate=rate, concurrency=concurrency,
                    on_result=on_result,
                    profile=profile,
                    browser_pool=pool,
                    user_agent=cfg.crawl.user_agent,
                    firecrawl_pool=fc_pool,
                )
            finally:
                if pool is not None:
                    await pool.aclose()
                if fc_pool is not None:
                    await fc_pool.aclose()

        fetched = asyncio.run(_run())
        out: dict = {"run_id": run_id, "new_fetches": fetched,
                     "by_status": statuses, "fetch_log": str(fetch_log)}
        if fc_pool is not None:
            out["firecrawl"] = {
                "calls_attempted": fc_pool.calls_attempted,
                "calls_succeeded": fc_pool.calls_succeeded,
                "credits_used": fc_pool.credits_used,
                "budget_remaining": fc_pool.budget_remaining(),
            }
        click.echo(json.dumps(out, indent=2))


@main.command()
@_root_opt
@_config_opt
@click.option("--run-id", required=True)
def extract(root: Path, config_path: Optional[Path], run_id: str):
    """Phase 3: HTML -> normalized markdown -> content hash."""
    _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    with _fail_run_on_crash(conn, run_id):
        record_run_phase(conn, run_id, "extract")
        # Stream the fetch.log synchronously (the async iter wrapper is overkill here).
        fl = paths.fetch_log_path(root, run_id)
        el = paths.extract_log_path(root, run_id)
        fetches = []
        if fl.exists():
            from .fetch import FetchResult
            with fl.open() as f:
                for line in f:
                    try:
                        fetches.append(FetchResult(**json.loads(line)))
                    except Exception:
                        continue
        n = extract_all(
            fetches, root=root, run_id=run_id, conn=conn,
            crawler_version=CRAWLER_VERSION, extract_log=el,
        )
        click.echo(json.dumps({"run_id": run_id, "extracted": n,
                               "extract_log": str(el)}, indent=2))


@main.command()
@_root_opt
@_config_opt
@click.option("--run-id", required=True)
def commit(root: Path, config_path: Optional[Path], run_id: str):
    """Phase 4: apply fetch+extract logs to manifest in one transaction."""
    _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    with _fail_run_on_crash(conn, run_id):
        record_run_phase(conn, run_id, "commit")
        counts = commit_phase(
            conn,
            paths.fetch_log_path(root, run_id),
            paths.extract_log_path(root, run_id),
            root=root, run_id=run_id,
        )
        click.echo(json.dumps({"run_id": run_id, "commit": counts}, indent=2))


@main.command("purge")
@_root_opt
@_config_opt
@click.option("--dry-run", is_flag=True,
              help="Show what would be purged without deleting anything.")
def purge_cmd(root: Path, config_path: Optional[Path], dry_run: bool):
    """Drop manifest rows whose plan decision is TOMBSTONE_PURGE.

    The decide phase already emits TOMBSTONE_PURGE for URLs that have been
    in GONE state past their per-tier tombstone TTL; `sift run` also runs
    this step between commit and publish. Use this standalone command
    when you want to purge without doing a full crawl run (e.g. after
    tweaking [tiers.*].tombstone_ttl_days)."""
    from .purge import purge_tombstones, PURGE_DECISION

    cfg = _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)
    profile = sites_mod.current_profile()
    now = datetime.now(timezone.utc)

    # Generate a plan into a throwaway path
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        pp = Path(td) / "plan.jsonl"
        plan_counts = plan_phase(
            conn, pp, now=now,
            extractor_version=EXTRACTOR_VERSION,
            normalizer_version=NORMALIZER_VERSION,
            profile=profile,
            cfg=cfg,
        )
        entries = load_plan(pp)

    candidates = [e for e in entries if e.decision == PURGE_DECISION]
    if dry_run:
        click.echo(json.dumps({
            "dry_run": True,
            "candidates": len(candidates),
            "sample_urls": [e.url for e in candidates[:10]],
            "plan_counts": plan_counts,
        }, indent=2, default=str))
        return

    with transaction(conn):
        result = purge_tombstones(conn, entries)
    click.echo(json.dumps({
        "purged": result["purged"],
        "candidates": result["candidates"],
        "plan_counts": plan_counts,
    }, indent=2, default=str))


@main.command("re-extract")
@_root_opt
@_config_opt
@click.option("--run-id", default=None,
              help="Run id for the re-extract artifacts (default: new timestamp + '-reextract')")
@click.option("--tier", "tiers", multiple=True, default=(),
              help="Restrict to these tiers (repeatable)")
@click.option("--include-frozen", is_flag=True,
              help="Also re-extract FROZEN rows (default: FRESH only). Use after a "
                   "FROZEN-tier first-fetch when you want to refresh historical extracts.")
@click.option("--publish/--no-publish", default=True,
              help="Run publish (consolidate + gates + symlink swap) after commit. "
                   "Default true.")
def re_extract_cmd(
    root: Path, config_path: Optional[Path], run_id: Optional[str],
    tiers: tuple[str, ...], include_frozen: bool, publish: bool,
):
    """Re-extract every eligible row from its cached raw blob (no network).

    Use when an extractor or normalizer version bump (or a profile swap) means
    stored content_hashes need refresh. Reads raw/, runs the CURRENT extractor
    pipeline against each blob, and writes new content_hashes via commit —
    naturally producing "changed" changelog entries with the proper
    old_hash → new_hash diff because the manifest still holds the prior hash.

    Idempotent: rows whose extractor_version + normalizer_version already match
    current versions are short-circuited (no work). Run after every
    EXTRACTOR_VERSION or NORMALIZER_VERSION bump."""
    import time as _time
    from .extract import re_extract_corpus

    _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)

    if not run_id:
        run_id = _new_run_id() + "-reextract"

    fresh_only = not include_frozen
    tier_filter = tiers if tiers else None

    with transaction(conn):
        record_run_start(conn, run_id, now_utc())
        record_run_phase(conn, run_id, "extract")

    with _fail_run_on_crash(conn, run_id):
        click.echo(f"re-extract run_id: {run_id}")
        if tier_filter:
            click.echo(f"tier filter: {sorted(tier_filter)}")
        click.echo(f"fresh_only: {fresh_only}")

        t0 = _time.perf_counter()
        fl, el, n_processed = re_extract_corpus(
            root, run_id=run_id, conn=conn, crawler_version=CRAWLER_VERSION,
            fresh_only=fresh_only, tiers=tier_filter,
        )
        extract_dt = round(_time.perf_counter() - t0, 2)
        click.echo(f"processed {n_processed} rows in {extract_dt}s")

        # Commit — produces changelog entries for any rows whose content_hash moved
        record_run_phase(conn, run_id, "commit")
        counts = commit_phase(conn, fl, el, root=root, run_id=run_id)
        click.echo(f"commit: {json.dumps(counts)}")

        if not publish:
            click.echo(json.dumps({
                "run_id": run_id, "extracted": n_processed,
                "commit": counts, "published": False, "extract_sec": extract_dt,
            }, indent=2))
            return

        # Publish — consolidate + 6 gates + symlink swap
        record_run_phase(conn, run_id, "publish")
        build_artifacts(conn, root, run_id)
        expected = conn.execute("SELECT COUNT(*) FROM manifest").fetchone()[0]
        ok, gates, snap = publish_phase(
            conn, root, run_id, started_at=now_utc(), expected_urls=expected,
        )
        state_counts = counts_by_state(conn)
        with transaction(conn):
            record_run_end(
                conn, run_id, now_utc(),
                status="succeeded" if ok else "degraded",
                counts_json=json.dumps(state_counts),
            )
        click.echo(json.dumps({
            "run_id": run_id,
            "extract_sec": extract_dt,
            "processed": n_processed,
            "commit": counts,
            "published": ok,
            "snapshot": str(snap),
            "gates": [{"name": n, "passed": p, "detail": d} for (n, p, d) in gates],
            "counts_by_state": state_counts,
        }, indent=2))
        if not ok:
            sys.exit(2)


@main.command()
@_root_opt
@_config_opt
@click.option("--run-id", required=True)
@click.option("--skip-artifacts", is_flag=True,
              help="Skip llms.txt / by_guide rollup (faster smoke tests)")
def publish(root: Path, config_path: Optional[Path], run_id: str, skip_artifacts: bool):
    """Phase 5: verify 5 gates, build artifacts, flip current symlink."""
    _load_cli_config(config_path)
    conn = open_db(paths.manifest_path(root))
    with _fail_run_on_crash(conn, run_id):
        record_run_phase(conn, run_id, "publish")
        if not skip_artifacts:
            build_artifacts(conn, root, run_id)
        expected = _total_rows(conn)
        started = now_utc()
        ok, gates, snap = publish_phase(
            conn, root, run_id, started_at=started, expected_urls=expected,
        )
        counts = counts_by_state(conn)
        with transaction(conn):
            record_run_end(
                conn, run_id, now_utc(),
                status="succeeded" if ok else "degraded",
                counts_json=json.dumps(counts),
            )
        out = {
            "run_id": run_id,
            "status": "published" if ok else "degraded",
            "gates": [{"name": n, "passed": p, "detail": d} for (n, p, d) in gates],
            "snapshot": str(snap),
            "counts_by_state": counts,
        }
        click.echo(json.dumps(out, indent=2))
        if not ok:
            sys.exit(2)


@main.command()
@_root_opt
@_config_opt
@click.option("--limit", type=int, default=None,
              help="Cap fetches in this run (useful for first-time smoke runs)")
@click.option("--rate", type=float, default=None,
              help="Requests per second per host (default: config crawl.rate_per_sec)")
@click.option("--concurrency", type=int, default=None,
              help="Concurrent in-flight requests (default: config crawl.concurrency)")
@click.option("--tier", "tiers", multiple=True, default=(),
              help="Only fetch URLs in these tiers (repeat: --tier LIVING --tier NEWS).")
@click.option("--coverage-base", type=str, default=None,
              help="For publish G3 coverage: base the terminal-state fraction on something other than total "
                   "manifest rows. 'filtered-tiers' = count of --tier rows (tier-filtered runs); "
                   "'planned' = min(--limit, total) so an intentional capped/partial crawl against a large "
                   "seed doesn't spuriously degrade.")
@click.option("--run-id", "run_id_opt", type=str, default=None,
              help="Use this run_id instead of a generated timestamp. Must be unique "
                   "(it's the runs-table primary key). Lets a caller mint the id up front "
                   "and correlate to the run — used by sift-mcp's index_url tool.")
@click.option("--firecrawl-fallback", is_flag=True, default=False,
              help="On 401/403 from the native fetcher, escalate that URL via "
                   "Firecrawl /v2/scrape. Costs Firecrawl credits; capped per "
                   "[crawl.firecrawl] max_credits_per_run. Requires "
                   "FIRECRAWL_API_KEY env. Overrides config.")
@click.option("--only-urls", "only_urls_path",
              type=click.Path(exists=True, path_type=Path), default=None,
              help="Scope the plan to URLs listed in this file (one URL per "
                   "line; blank + #-comment lines skipped). Rows outside the "
                   "set are SKIPPED entirely — not planned, not fetched. Use "
                   "for targeted backfills triggered by sift-mcp's index_url "
                   "tool so adding a single URL doesn't trigger a full-corpus "
                   "expansion.")
def run(root: Path, config_path: Optional[Path],
        limit: Optional[int], rate: Optional[float],
        concurrency: Optional[int],
        tiers: tuple[str, ...], coverage_base: Optional[str],
        run_id_opt: Optional[str], firecrawl_fallback: bool,
        only_urls_path: Optional[Path]):
    """Run plan -> fetch -> extract -> commit -> publish end-to-end with per-phase timing.

    Exit codes (operationally meaningful for cron / CI wrappers):
      0  fully published — all gates passed, current/ symlink flipped
      1  pipeline error — a phase crashed before publish could even attempt
      2  degraded — pipeline ran but one or more publish gates failed
                    (snapshot.json is still written with status=degraded;
                     current/ does NOT flip)
    """
    cfg = _load_cli_config(config_path)
    rate = rate if rate is not None else cfg.crawl.rate_per_sec
    concurrency = concurrency if concurrency is not None else cfg.crawl.concurrency
    import time as _time
    timings: dict[str, float] = {}

    def _phase(name: str):
        t0 = _time.perf_counter()
        return name, t0

    def _end(phase: tuple[str, float]) -> float:
        name, t0 = phase
        dt = _time.perf_counter() - t0
        timings[name] = round(dt, 2)
        click.echo(f"  [{name} {dt:.2f}s]")
        return dt

    overall_t0 = _time.perf_counter()
    conn = open_db(paths.manifest_path(root))
    init_schema(conn)
    run_id = run_id_opt or _new_run_id()
    now = datetime.now(timezone.utc)
    with transaction(conn):
        record_run_start(conn, run_id, now_utc())
        record_run_phase(conn, run_id, "plan")

    with _fail_run_on_crash(conn, run_id):
        # PLAN
        ph = _phase("plan")
        pp = paths.plan_path(root, run_id)
        profile = sites_mod.current_profile()
        only_urls: Optional[set[str]] = None
        if only_urls_path is not None:
            only_urls = _read_only_urls(only_urls_path)
            click.echo(f"plan-scope: --only-urls limits to {len(only_urls)} URL(s) "
                       f"from {only_urls_path}")
        plan_counts = plan_phase(
            conn, pp, now=now,
            extractor_version=EXTRACTOR_VERSION,
            normalizer_version=NORMALIZER_VERSION,
            profile=profile,
            cfg=cfg,
            only_urls=only_urls,
        )
        click.echo(f"plan: {json.dumps(plan_counts)}")
        _end(ph)

        # FETCH
        plan_entries = load_plan(pp)
        fetchable = [p for p in plan_entries if p.decision in ("FETCH", "FETCH_CONDITIONAL")]
        if tiers:
            tier_set = set(tiers)
            fetchable = [p for p in fetchable if p.tier in tier_set]
        if limit is not None:
            fetchable = fetchable[:limit]
        inputs = [
            FetchInput(url=p.url, decision=p.decision, etag=p.etag, last_modified=p.last_modified)
            for p in fetchable
        ]
        click.echo(f"fetch input: {len(inputs)} URLs"
                   + (f" (tier filter: {sorted(tiers)})" if tiers else ""))
        record_run_phase(conn, run_id, "fetch")
        fl = paths.fetch_log_path(root, run_id)
        ph = _phase("fetch")
        needs_browser_run = cfg.browser.enabled and any(
            profile.requires_browser(p.url) for p in fetchable
        )
        if needs_browser_run:
            # Probe only when a SPA URL is actually pending — a missing
            # Playwright then hard-fails this run with a clear install hint
            # (and the guard records a terminal 'failed'). A run with no SPA
            # URL never reaches here, so a mostly-HTTP corpus is unaffected.
            from .browser import check_browser_available
            check_browser_available()
        fc_pool = _build_firecrawl_pool(cfg, firecrawl_fallback)
        # SSRF guard for redirect-following: only store bodies whose final host
        # is on the configured allow-list. Empty allow-list → None (no check).
        allowed_hosts = frozenset(h.lower() for h in cfg.seed.host_allow) or None

        async def _do_fetch() -> int:
            pool = None
            if needs_browser_run:
                from .browser import BrowserPool
                pool = BrowserPool(cfg.browser.concurrency, cfg.browser)
            try:
                return await fetch_all(
                    inputs, root, fl,
                    rate=rate, concurrency=concurrency,
                    profile=profile,
                    browser_pool=pool,
                    user_agent=cfg.crawl.user_agent,
                    firecrawl_pool=fc_pool,
                    allowed_hosts=allowed_hosts,
                )
            finally:
                if pool is not None:
                    await pool.aclose()
                if fc_pool is not None:
                    await fc_pool.aclose()

        n_fetched = asyncio.run(_do_fetch())
        click.echo(f"fetched: {n_fetched}")
        fetch_dt = _end(ph)

        # EXTRACT
        record_run_phase(conn, run_id, "extract")
        from .fetch import FetchResult
        fetches = []
        if fl.exists():
            with fl.open() as f:
                for line in f:
                    try:
                        fetches.append(FetchResult(**json.loads(line)))
                    except Exception:
                        continue
        el = paths.extract_log_path(root, run_id)
        ph = _phase("extract")
        n_extr = extract_all(
            fetches, root=root, run_id=run_id, conn=conn,
            crawler_version=CRAWLER_VERSION, extract_log=el,
        )
        click.echo(f"extracted: {n_extr}")
        _end(ph)

        # COMMIT
        record_run_phase(conn, run_id, "commit")
        ph = _phase("commit")
        c_counts = commit_phase(conn, fl, el, root=root, run_id=run_id)
        click.echo(f"commit: {json.dumps(c_counts)}")
        _end(ph)

        # PURGE — drop manifest rows whose plan decision was TOMBSTONE_PURGE.
        # Runs after commit so committed fetches can't be racing the delete,
        # and before publish so the coverage gate sees the post-purge state.
        record_run_phase(conn, run_id, "purge")
        ph = _phase("purge")
        from .purge import purge_tombstones
        with transaction(conn):
            purge_counts = purge_tombstones(conn, plan_entries)
        if purge_counts["candidates"] > 0:
            click.echo(f"purge: {json.dumps(purge_counts)}")
        _end(ph)

        # PUBLISH
        record_run_phase(conn, run_id, "publish")
        ph = _phase("publish")
        build_artifacts(conn, root, run_id)
        # Coverage base: by default the total manifest rows (so a tier-filtered run
        # will degrade gate G3). Pass --coverage-base to make it meaningful for
        # a filtered run (e.g. count of LIVING+NEWS+CURRENT_FORMS rows).
        if coverage_base == "filtered-tiers" and tiers:
            tier_list = sorted(tiers)
            placeholders = ",".join(["?"] * len(tier_list))
            expected = conn.execute(
                f"SELECT COUNT(*) FROM manifest WHERE tier IN ({placeholders})",
                tier_list,
            ).fetchone()[0]
        elif coverage_base == "planned":
            # Intentional capped/partial crawl: measure coverage against what
            # this run set out to fetch (the --limit cap), not the full seed —
            # otherwise `--limit N` against a large sitemap always degrades G3.
            total = _total_rows(conn)
            expected = min(limit, total) if limit else total
        else:
            expected = _total_rows(conn)
        ok, gates, snap = publish_phase(
            conn, root, run_id, started_at=now_utc(), expected_urls=expected,
        )
        state_counts = counts_by_state(conn)
        with transaction(conn):
            record_run_end(
                conn, run_id, now_utc(),
                status="succeeded" if ok else "degraded",
                counts_json=json.dumps(state_counts),
            )
        _end(ph)

        total = round(_time.perf_counter() - overall_t0, 2)
        throughput = round(n_fetched / fetch_dt, 2) if n_fetched and fetch_dt > 0 else 0
        failed_gates = [n for (n, p, _d) in gates if not p]
        run_summary: dict = {
            "run_id": run_id,
            "published": ok,
            "status": "published" if ok else "degraded",
            "snapshot": str(snap),
            "gates": [{"name": n, "passed": p, "detail": d} for (n, p, d) in gates],
            "failed_gates": failed_gates,
            "counts_by_state": state_counts,
            "purge": purge_counts,
            "timings_sec": timings,
            "total_sec": total,
            "fetch_throughput_req_per_sec": throughput,
            "exit_code": 0 if ok else 2,
        }
        if fc_pool is not None:
            run_summary["firecrawl"] = {
                "calls_attempted": fc_pool.calls_attempted,
                "calls_succeeded": fc_pool.calls_succeeded,
                "credits_used": fc_pool.credits_used,
                "budget_remaining": fc_pool.budget_remaining(),
            }
        click.echo(json.dumps(run_summary, indent=2))
        # Exit codes (see docstring): 0 fully published, 1 pipeline error (Click
        # bubbles unhandled exceptions automatically), 2 degraded (gates failed).
        if not ok:
            sys.exit(2)


@main.command("backup")
@_root_opt
@click.option("--to", "dest_path", type=click.Path(path_type=Path), default=None,
              help="Destination. Default: <root>/backups/manifest-<UTC>.db")
@click.option("--keep", type=int, default=None,
              help="After backup, keep only the N most recent backup files in "
                   "<root>/backups/ (rotate older ones). Default: keep all.")
def backup_cmd(root: Path, dest_path: Optional[Path], keep: Optional[int]):
    """Online SQLite backup of manifest.db to a separate path.

    Uses sqlite3.Connection.backup() — safe to run while the manifest is being
    written to. Writes a copy + sha256 + size to the destination, then
    optionally rotates older backups in <root>/backups/.

    Suggested cron: nightly, with --keep 14 (two-week retention). For
    off-machine durability, point --to at a mounted volume or follow up with
    rclone/rsync to remote storage.
    """
    import sqlite3 as _sqlite3
    import hashlib as _hashlib
    import time as _time

    src_path = paths.manifest_path(root)
    if not src_path.exists():
        raise click.UsageError(f"no manifest.db at {src_path}")

    if dest_path is None:
        bdir = paths.backups_dir(root)
        bdir.mkdir(parents=True, exist_ok=True)
        ts = now_utc().replace(":", "").replace("-", "")  # 20260524T223500Z form
        dest_path = bdir / f"manifest-{ts}.db"
    else:
        dest_path.parent.mkdir(parents=True, exist_ok=True)

    # Online backup — works while the source is open for writes elsewhere
    t0 = _time.perf_counter()
    src = _sqlite3.connect(f"file:{src_path}?mode=ro", uri=True)
    dst = _sqlite3.connect(str(dest_path))
    try:
        src.backup(dst)
    finally:
        dst.close()
        src.close()
    dt = round(_time.perf_counter() - t0, 2)

    # Provenance
    sha = _hashlib.sha256()
    with dest_path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            sha.update(chunk)
    size = dest_path.stat().st_size

    out = {
        "ok": True,
        "source": str(src_path),
        "destination": str(dest_path),
        "size_bytes": size,
        "sha256": sha.hexdigest(),
        "elapsed_sec": dt,
    }

    # Optional rotation in the default backups dir
    if keep is not None and keep > 0:
        bdir = paths.backups_dir(root)
        if bdir.exists():
            backups = sorted(
                bdir.glob("manifest-*.db"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            to_delete = backups[keep:]
            for f in to_delete:
                f.unlink()
            out["rotated"] = {
                "kept": len(backups) - len(to_delete),
                "deleted": [str(f.name) for f in to_delete],
            }

    click.echo(json.dumps(out, indent=2))


@main.command("verify-backup")
@_root_opt
@click.argument("backup_path", type=click.Path(exists=True, path_type=Path))
def verify_backup_cmd(root: Path, backup_path: Path):
    """Verify a backup is a valid, complete SQLite file with the manifest schema."""
    import sqlite3 as _sqlite3
    try:
        conn = _sqlite3.connect(f"file:{backup_path}?mode=ro", uri=True)
        # Integrity check (SQLite-internal pages + b-tree consistency)
        result = conn.execute("PRAGMA integrity_check").fetchone()
        if result[0] != "ok":
            click.echo(json.dumps({"ok": False, "reason": f"integrity_check: {result[0]}"}, indent=2))
            sys.exit(2)
        # Schema sanity — confirm the manifest table is present + has rows
        tables = {r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )}
        missing = {"manifest", "runs"} - tables
        if missing:
            click.echo(json.dumps({"ok": False, "reason": f"missing tables: {sorted(missing)}"}, indent=2))
            sys.exit(2)
        rows = conn.execute("SELECT COUNT(*) FROM manifest").fetchone()[0]
        conn.close()
        click.echo(json.dumps({
            "ok": True,
            "backup": str(backup_path),
            "tables": sorted(tables),
            "manifest_rows": rows,
        }, indent=2))
    except _sqlite3.DatabaseError as e:
        click.echo(json.dumps({"ok": False, "reason": f"sqlite error: {e}"}, indent=2))
        sys.exit(2)


@main.command("verify-snapshot")
@_root_opt
@_config_opt
@click.option("--run-id", default=None, help="Defaults to current/ symlink target")
def verify_snapshot_cmd(root: Path, config_path: Optional[Path], run_id: Optional[str]):
    """Recompute the Merkle root from the manifest and compare to snapshot.json.

    O(N) verification — the snapshot is bit-identical to publish time iff the
    recomputed root matches the stored root. Catches any modification to
    content_hash values across the entire corpus."""
    _load_cli_config(config_path)
    if not run_id:
        cur = paths.current_symlink(root)
        if not cur.exists():
            raise click.UsageError("no --run-id and no current/ symlink")
        run_id = cur.resolve().name
    snap_path = paths.snapshot_path(root, run_id)
    if not snap_path.exists():
        raise click.UsageError(f"snapshot.json missing for run {run_id}")
    try:
        snap = json.loads(snap_path.read_text())
    except (OSError, ValueError) as e:
        click.echo(json.dumps({"ok": False, "reason": f"snapshot.json unreadable: {e}"}, indent=2))
        sys.exit(2)
    stored = (snap.get("integrity") or {}).get("merkle_root")
    if not stored:
        click.echo(json.dumps({"ok": False, "reason": "snapshot has no merkle_root (pre-integrity-v1 snapshot)"}, indent=2))
        sys.exit(2)
    conn = open_db(paths.manifest_path(root))
    from .manifest import iter_all as _iter_all
    rows = [(r.url, r.content_hash) for r in _iter_all(conn)
            if r.state in ("FRESH", "FROZEN") and r.content_hash]
    recomputed, leaf_count = integrity_mod.compute_corpus_root(rows)
    ok = recomputed == stored
    click.echo(json.dumps({
        "ok": ok, "run_id": run_id,
        "stored_root": stored, "recomputed_root": recomputed,
        "leaf_count_stored": (snap.get("integrity") or {}).get("leaf_count"),
        "leaf_count_recomputed": leaf_count,
    }, indent=2))
    if not ok:
        sys.exit(2)


@main.command("verify-changelog")
@_root_opt
@_config_opt
def verify_changelog_cmd(root: Path, config_path: Optional[Path]):
    """Walk changelog.jsonl and verify every entry's prev_hash + entry_hash chain.

    Any tampering — silent insertion, deletion, or field modification — breaks
    the chain at that point and is reported with the offending entry index."""
    _load_cli_config(config_path)
    cl = paths.changelog_path(root)
    if not cl.exists():
        click.echo(json.dumps({"ok": True, "entries": 0, "reason": "no changelog yet"}, indent=2))
        return
    entries = []
    with cl.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError as e:
                click.echo(json.dumps({"ok": False, "reason": f"parse error: {e}"}, indent=2))
                sys.exit(2)
    ok, bad_idx, reason = integrity_mod.verify_chain(entries)
    out = {"ok": ok, "entries": len(entries)}
    if not ok:
        out["first_bad_index"] = bad_idx
        out["reason"] = reason
    click.echo(json.dumps(out, indent=2))
    if not ok:
        sys.exit(2)


@main.command("verify-signature")
@_root_opt
@_config_opt
@click.option("--run-id", default=None)
def verify_signature_cmd(root: Path, config_path: Optional[Path], run_id: Optional[str]):
    """Verify the GPG detach-signature on snapshot.json (if signing is enabled)."""
    import subprocess
    _load_cli_config(config_path)
    if not run_id:
        cur = paths.current_symlink(root)
        if not cur.exists():
            raise click.UsageError("no --run-id and no current/ symlink")
        run_id = cur.resolve().name
    snap = paths.snapshot_path(root, run_id)
    sig = snap.with_suffix(snap.suffix + ".sig")
    if not sig.exists():
        click.echo(json.dumps({"ok": False, "reason": "no .sig file (signing not configured?)"}, indent=2))
        sys.exit(2)
    try:
        result = subprocess.run(
            ["gpg", "--verify", str(sig), str(snap)],
            check=True, capture_output=True, timeout=30,
        )
        click.echo(json.dumps({"ok": True, "snapshot": str(snap),
                               "signature": str(sig),
                               "gpg_output": result.stderr.decode()}, indent=2))
    except subprocess.CalledProcessError as e:
        click.echo(json.dumps({"ok": False, "reason": "gpg verify failed",
                               "gpg_output": e.stderr.decode()}, indent=2))
        sys.exit(2)
    except FileNotFoundError:
        click.echo(json.dumps({"ok": False, "reason": "gpg not installed"}, indent=2))
        sys.exit(2)


@main.command("verify")
@_root_opt
@_config_opt
@click.option("--run-id", default=None)
@click.option("--skip-signature", is_flag=True,
              help="Skip GPG signature check (e.g. when not signing)")
def verify_all_cmd(root: Path, config_path: Optional[Path], run_id: Optional[str],
                   skip_signature: bool):
    """Run all integrity verifications: Merkle root + changelog chain + (optional) GPG.

    Exit 0 iff every check passes. Exit 2 on any failure with diagnostics."""
    _load_cli_config(config_path)
    if not run_id:
        cur = paths.current_symlink(root)
        if cur.exists():
            run_id = cur.resolve().name

    all_ok = True
    results: dict = {}

    # Merkle
    if run_id:
        snap_path = paths.snapshot_path(root, run_id)
        if snap_path.exists():
            try:
                snap = json.loads(snap_path.read_text())
            except (OSError, ValueError):
                snap = {}
            stored = (snap.get("integrity") or {}).get("merkle_root")
            if stored:
                conn = open_db(paths.manifest_path(root))
                from .manifest import iter_all as _iter_all
                rows = [(r.url, r.content_hash) for r in _iter_all(conn)
                        if r.state in ("FRESH", "FROZEN") and r.content_hash]
                recomputed, _ = integrity_mod.compute_corpus_root(rows)
                ok = recomputed == stored
                results["merkle_root"] = {
                    "ok": ok,
                    "stored": stored[:16] + "...",
                    "recomputed": (recomputed or "")[:16] + "...",
                }
                all_ok = all_ok and ok
            else:
                results["merkle_root"] = {"ok": False, "reason": "snapshot has no merkle_root"}
                all_ok = False
        else:
            results["merkle_root"] = {"ok": False, "reason": f"no snapshot.json for run {run_id}"}
            all_ok = False
    else:
        results["merkle_root"] = {"ok": False, "reason": "no --run-id and no current/ symlink"}
        all_ok = False

    # Changelog
    cl = paths.changelog_path(root)
    if cl.exists():
        try:
            with cl.open() as f:
                entries = [json.loads(line) for line in f if line.strip()]
        except (OSError, json.JSONDecodeError) as e:
            results["changelog"] = {"ok": False, "entries": 0, "reason": f"malformed changelog: {e}"}
            all_ok = False
        else:
            chain_ok, bad_idx, reason = integrity_mod.verify_chain(entries)
            results["changelog"] = {"ok": chain_ok, "entries": len(entries)}
            if not chain_ok:
                results["changelog"]["first_bad_index"] = bad_idx
                results["changelog"]["reason"] = reason
            all_ok = all_ok and chain_ok
    else:
        results["changelog"] = {"ok": True, "entries": 0, "reason": "no changelog yet"}

    # Signature (optional)
    if not skip_signature and run_id:
        import subprocess
        snap = paths.snapshot_path(root, run_id)
        sig = snap.with_suffix(snap.suffix + ".sig")
        if sig.exists():
            try:
                subprocess.run(["gpg", "--verify", str(sig), str(snap)],
                               check=True, capture_output=True, timeout=30)
                results["signature"] = {"ok": True}
            except subprocess.CalledProcessError as e:
                results["signature"] = {"ok": False, "reason": e.stderr.decode()[:200]}
                all_ok = False
            except FileNotFoundError:
                results["signature"] = {"ok": True, "reason": "gpg not installed; skipping"}
        else:
            results["signature"] = {"ok": True, "reason": "no .sig (signing disabled)"}

    click.echo(json.dumps({"ok": all_ok, "run_id": run_id, **results}, indent=2))
    if not all_ok:
        sys.exit(2)


@main.command("manifest-query")
@_root_opt
@click.argument("sql")
@click.option("--format", "fmt", type=click.Choice(["json", "tsv"]), default="json")
def manifest_query(root: Path, sql: str, fmt: str):
    """Run a read-only SELECT against manifest.db.

    Designed as the canonical tool an agent harness exposes for structured
    manifest queries. Refuses anything that isn't a SELECT to keep the
    surface safe."""
    s = sql.strip().lower()
    if not s.startswith("select") and not s.startswith("with"):
        raise click.UsageError("only SELECT/WITH queries allowed")
    conn = open_db(paths.manifest_path(root))
    rows = list(conn.execute(sql))
    if not rows:
        click.echo("[]" if fmt == "json" else "")
        return
    cols = rows[0].keys()
    if fmt == "tsv":
        click.echo("\t".join(cols))
        for r in rows:
            click.echo("\t".join(str(r[c]) if r[c] is not None else "" for c in cols))
    else:
        click.echo(json.dumps([dict(r) for r in rows], indent=2, default=str))


@main.command()
@_root_opt
def status(root: Path):
    """Show counts and the currently-published run."""
    from .status import compute_status_summary
    click.echo(json.dumps(compute_status_summary(root), indent=2, default=str))


if __name__ == "__main__":
    main()
